# Generated by Django 2.1b1 on 2018-07-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndApp', '0006_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='title',
            field=models.CharField(default='title', max_length=100),
        ),
        migrations.AddField(
            model_name='component',
            name='title',
            field=models.CharField(default='title', max_length=100),
        ),
        migrations.AddField(
            model_name='level',
            name='title',
            field=models.CharField(default='title', max_length=100),
        ),
        migrations.AddField(
            model_name='payperiod',
            name='title',
            field=models.CharField(default='title', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default='title', max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='title',
            field=models.CharField(default='title', max_length=100),
        ),
    ]
